name: Convert Markdown to HTML

on:
  push:
    paths:
      - '**.md'
    branches: [ main ]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: npm install -g markdown-to-html-cli
        
      - name: Convert Markdown to HTML
        run: |
          for file in $(find . -name "*.md"); do
            if [ "$file" != "./README.md" ]; then
              html_file="${file%.md}.html"
              markdown-to-html-cli -s github -o "$html_file" "$file"
            fi
          done
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.html
          git commit -m "Convert Markdown to HTML" || echo "No changes to commit"
          git push
